# Generated by Django 5.0.1 on 2024-01-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="discription",
        ),
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
